# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      maximumCpuCount: true
      msbuildArchitecture: 'x64'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)\Core\bin\$(buildConfiguration)'
      artifact: 'Assemblies ($(buildConfiguration))'
      publishLocation: 'pipeline'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)\Core.Tests\bin'
      artifact: 'Tests'
      publishLocation: 'pipeline'
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: '$(Build.SourcesDirectory)\Core\Core.csproj'
      versioningScheme: 'off'
      buildProperties: 'PackageVersion=1.0.0-ci+$(Build.SourceVersion)'
      basePath: '$(Build.SourcesDirectory)\Core\bin\$(buildConfiguration)'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'NuGet package ($(buildConfiguration))'
      publishLocation: 'pipeline'
  
- job: Test
  displayName: 'Test'
  dependsOn: Build
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'Tests'
      targetPath: '$(Pipeline.Workspace)'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '$(Pipeline.Workspace)\$(buildConfiguration)\**\PresentationBase.Core.Tests.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runTestsInIsolation: true
      codeCoverageEnabled: true
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'